# Install lm_sensors package and scan for sensors
class lm_sensors::install {
  # Install lm_sensors

  ensure_packages($lm_sensors::package_ensure, {
    ensure => $lm_sensors::package_ensure,
    notify => Exec['sensors-detect'],
    })


    ensure_packages($lm_sensors::package)

    # Scan for hardware sensors
    exec { 'sensors-detect':
      command => $lm_sensors::exec_command,
      unless  => "/bin/grep \"Generated by sensors-detect\" ${lm_sensors::config_file}",
      notify  => Service['lm_sensors'],
      require => Package['lm_sensors'],
    }
}
